#!/bin/bash
cd /tmp/rom

source build/envsetup.sh
lunch cherish_whyred-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
mka bacon -j$(nproc --all) &
sleep 45m
kill %1
ccache -s
